name: Validate backend application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      working-directory: app/backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt

    - name: Run pytest
      working-directory: app/backend
      run: python -m pytest
      env:
        AZURE_CLIENT_ID: 00000000-0000-0000-0000-000000000000
        AZURE_CLIENT_SECRET: Not-The-Client-Secret
        AZURE_TENANT_ID: 00000000-0000-0000-0000-000000000000